name       : hidapi
version    : 0.8.0_rc1
release    : 1
source     :
    - https://github.com/signal11/hidapi/archive/hidapi-0.8.0-rc1.tar.gz : 3c147200bf48a04c1e927cd81589c5ddceff61e6dac137a605f6ac9793f4af61
license    : GPL-3.0
component  : programming
summary    : Simple library for communicating with USB and Bluetooth HID devices on Linux, Mac, and Windows.
description: |
    Simple library for communicating with USB and Bluetooth HID devices on Linux, Mac, and Windows.
builddeps  :
    - pkgconfig(libusb-1.0)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
    # Remove all the doc stuff, it's just licensing
    rm -rf $installdir/usr/share/
