name       : hidapi
version    : 0.9.0
release    : 3
source     :
    - https://github.com/libusb/hidapi/archive/hidapi-0.9.0.tar.gz : 630ee1834bdd5c5761ab079fd04f463a89585df8fcae51a7bfe4229b1e02a652
license    : GPL-3.0-or-later
component  : programming
summary    : Simple library for communicating with USB and Bluetooth HID devices
description: |
    Simple library for communicating with USB and Bluetooth HID devices on Linux, Mac, and Windows.
builddeps  :
    - pkgconfig32(libusb-1.0)
emul32     : yes
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
    # Remove all the doc stuff, it's just licensing
    rm -rf $installdir/usr/share/
