name       : hidapi
version    : 0.11.0
release    : 7
source     :
    - https://github.com/libusb/hidapi/archive/refs/tags/hidapi-0.11.0.tar.gz : 391d8e52f2d6a5cf76e2b0c079cfefe25497ba1d4659131297081fc0cd744632
license    : GPL-3.0-or-later
component  : programming
homepage   : https://github.com/libusb/hidapi/
summary    : Simple library for communicating with USB and Bluetooth HID devices
description: |
    Simple library for communicating with USB and Bluetooth HID devices on Linux, Mac, and Windows.
builddeps  :
    - pkgconfig32(libusb-1.0)
emul32     : yes
setup      : |
    %cmake_ninja -DCMAKE_INSTALL_LIBDIR=lib%LIBSUFFIX%
build      : |
    %ninja_build
install    : |
    %ninja_install
    # Remove all the doc stuff, it's just licensing
    rm -rf $installdir/usr/share/
