name       : hidapi
version    : 0.8.0_rc1
release    : 2
source     :
    - git|https://github.com/signal11/hidapi.git : a6a622ffb680c55da0de787ff93b80280498330f
license    : GPL-3.0-or-later
component  : programming
summary    : Simple library for communicating with USB and Bluetooth HID devices
description: |
    Simple library for communicating with USB and Bluetooth HID devices on Linux, Mac, and Windows.
builddeps  :
    - pkgconfig32(libusb-1.0)
emul32     : yes
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
    # Remove all the doc stuff, it's just licensing
    rm -rf $installdir/usr/share/
